<?php
//工場ステージの情報
return array(	//各項目詳細はrank1.phpを参照のこと
	'enemy' => array(
		0 => array(
			array(
				'enemyNum' => 401,
				'rate' => 40,
			),
			array(
				'enemyNum' => 402,
				'rate' => 30,
			),
			array(
				'enemyNum' => 403,
				'rate' => 30,
			),
		),
	),
	//'boss' => 404,
	'boss' => array(
					'1'=>'',
					'2'=>'',
					'3'=>'',
					'4'=>'',
					'5'=>'404',
	),
	'stage' => array(
		'1' => array(
			'name' => 'ガレージ',
			'fee' => 270,
			'startDirection' => 0,
			'event' => array(
				'none' => 70,
				'drop' => 5,
				'encount' => 25,
			),
			'goal' => array(
				array(
					'rate' => 80,
					'category' => 2,
					'id' => 4,
					'char' => '',
					'value' => 0,
					'countMin' => 2,
					'countMax' => 3,
				),
				array(
					'rate' => 20,
					'category' => 1,
					'id' => 0,
					'char' => '',
					'value' => 0,
					'countMin' => 400,
					'countMax' => 400,
				),
			),
			'drop' => array(
				array(
					'rate' => 80,
					'category' => 2,
					'id' => 4,
					'char' => '',
					'value' => 0,
					'countMin' => 1,
					'countMax' => 4,
				),
				array(
					'rate' => 20,
					'category' => 1,
					'id' => 0,
					'char' => '',
					'value' => 0,
					'countMin' => 160,
					'countMax' => 170,
				),
			),
		),
		'2' => array(
			'name' => '機械操作室',
			'fee' => 290,
			'startDirection' => 1,
			'event' => array(
				'none' => 70,
				'drop' => 5,
				'encount' => 25,
			),
			'goal' => array(
				array(
					'rate' => 80,
					'category' => 2,
					'id' => 4,
					'char' => '',
					'value' => 0,
					'countMin' => 1,
					'countMax' => 4,
				),
				array(
					'rate' => 20,
					'category' => 1,
					'id' => 0,
					'char' => '',
					'value' => 0,
					'countMin' => 400,
					'countMax' => 420,
				),
			),
			'drop' => array(
				array(
					'rate' => 80,
					'category' => 2,
					'id' => 4,
					'char' => '',
					'value' => 0,
					'countMin' => 2,
					'countMax' => 5,
				),
				array(
					'rate' => 20,
					'category' => 1,
					'id' => 0,
					'char' => '',
					'value' => 0,
					'countMin' => 170,
					'countMax' => 180,
				),
			),
		),
		'3' => array(
			'name' => '作業場',
			'fee' => 310,
			'startDirection' => 3,
			'event' => array(
				'none' => 70,
				'drop' => 5,
				'encount' => 25,
			),
			'goal' => array(
				array(
					'rate' => 80,
					'category' => 2,
					'id' => 4,
					'char' => '',
					'value' => 0,
					'countMin' => 3,
					'countMax' => 6,
				),
				array(
					'rate' => 20,
					'category' => 1,
					'id' => 0,
					'char' => '',
					'value' => 0,
					'countMin' => 420,
					'countMax' => 440,
				),
			),
			'drop' => array(
				array(
					'rate' => 80,
					'category' => 2,
					'id' => 4,
					'char' => '',
					'value' => 0,
					'countMin' => 2,
					'countMax' => 4,
				),
				array(
					'rate' => 20,
					'category' => 1,
					'id' => 0,
					'char' => '',
					'value' => 0,
					'countMin' => 180,
					'countMax' => 190,
				),
			),
		),
		'4' => array(
			'name' => '開発室',
			'fee' => 330,
			'startDirection' => 0,
			'event' => array(
				'none' => 70,
				'drop' => 5,
				'encount' => 25,
			),
			'goal' => array(
				array(
					'rate' => 80,
					'category' => 2,
					'id' => 4,
					'char' => '',
					'value' => 0,
					'countMin' => 2,
					'countMax' => 4,
				),
				array(
					'rate' => 20,
					'category' => 1,
					'id' => 0,
					'char' => '',
					'value' => 0,
					'countMin' => 440,
					'countMax' => 460,
				),
			),
			'drop' => array(
				array(
					'rate' => 80,
					'category' => 2,
					'id' => 4,
					'char' => '',
					'value' => 0,
					'countMin' => 2,
					'countMax' => 5,
				),
				array(
					'rate' => 20,
					'category' => 1,
					'id' => 0,
					'char' => '',
					'value' => 0,
					'countMin' => 190,
					'countMax' => 200,
				),
			),
		),
		'5' => array(
			'name' => 'メインラボ',
			'fee' => 350,
			'startDirection' => 0,
			'event' => array(
				'none' => 70,
				'drop' => 5,
				'encount' => 25,
			),
			'goal' => array(
				array(
					'rate' => 80,
					'category' => 2,
					'id' => 4,
					'char' => '',
					'value' => 0,
					'countMin' => 2,
					'countMax' => 5,
				),
				array(
					'rate' => 20,
					'category' => 1,
					'id' => 0,
					'char' => '',
					'value' => 0,
					'countMin' => 460,
					'countMax' => 480,
				),
			),
			'drop' => array(
				array(
					'rate' => 80,
					'category' => 2,
					'id' => 4,
					'char' => '',
					'value' => 0,
					'countMin' => 1,
					'countMax' => 3,
				),
				array(
					'rate' => 20,
					'category' => 1,
					'id' => 0,
					'char' => '',
					'value' => 0,
					'countMin' => 200,
					'countMax' => 210,
				),
			),
		),
	),
);
