<?php
//洞窟ステージの情報
return array(	//各項目詳細はrank1.phpを参照のこと
	'enemy' => array(
		0 => array(
			array(
				'enemyNum' => 201,
				'rate' => 40,
			),
			array(
				'enemyNum' => 202,
				'rate' => 30,
			),
			array(
				'enemyNum' => 203,
				'rate' => 30,
			),
		),
	),
	//'boss' => 204,
	'boss' => array(
					'1'=>'',
					'2'=>'',
					'3'=>'',
					'4'=>'',
					'5'=>'204',
	),
	'stage' => array(
		'1' => array(
			'name' => '奥の見えない入口',
			'fee' => 70,
			'startDirection' => 0,
			'event' => array(
				'none' => 70,
				'drop' => 5,
				'encount' => 25,
			),
			'goal' => array(
				array(
					'rate' => 80,
					'category' => 2,
					'id' => 2,
					'char' => '',
					'value' => 0,
					'countMin' => 2,
					'countMax' => 5,
				),
				array(
					'rate' => 20,
					'category' => 1,
					'id' => 0,
					'char' => '',
					'value' => 0,
					'countMin' => 200,
					'countMax' => 200,
				),
			),
			'drop' => array(
				array(
					'rate' => 80,
					'category' => 2,
					'id' => 2,
					'char' => '',
					'value' => 0,
					'countMin' => 3,
					'countMax' => 6,
				),
				array(
					'rate' => 20,
					'category' => 1,
					'id' => 0,
					'char' => '',
					'value' => 0,
					'countMin' => 60,
					'countMax' => 70,
				),
			),
		),
		'2' => array(
			'name' => '足場の悪い道',
			'fee' => 90,
			'startDirection' => 1,
			'event' => array(
				'none' => 70,
				'drop' => 5,
				'encount' => 25,
			),
			'goal' => array(
				array(
					'rate' => 80,
					'category' => 2,
					'id' => 2,
					'char' => '',
					'value' => 0,
					'countMin' => 1,
					'countMax' => 4,
				),
				array(
					'rate' => 20,
					'category' => 1,
					'id' => 0,
					'char' => '',
					'value' => 0,
					'countMin' => 200,
					'countMax' => 220,
				),
			),
			'drop' => array(
				array(
					'rate' => 80,
					'category' => 2,
					'id' => 2,
					'char' => '',
					'value' => 0,
					'countMin' => 1,
					'countMax' => 2,
				),
				array(
					'rate' => 20,
					'category' => 1,
					'id' => 0,
					'char' => '',
					'value' => 0,
					'countMin' => 70,
					'countMax' => 80,
				),
			),
		),
		'3' => array(
			'name' => '薄暗い岩場',
			'fee' => 110,
			'startDirection' => 3,
			'event' => array(
				'none' => 70,
				'drop' => 5,
				'encount' => 25,
			),
			'goal' => array(
				array(
					'rate' => 80,
					'category' => 2,
					'id' => 2,
					'char' => '',
					'value' => 0,
					'countMin' => 2,
					'countMax' => 5,
				),
				array(
					'rate' => 20,
					'category' => 1,
					'id' => 0,
					'char' => '',
					'value' => 0,
					'countMin' => 220,
					'countMax' => 240,
				),
			),
			'drop' => array(
				array(
					'rate' => 80,
					'category' => 2,
					'id' => 2,
					'char' => '',
					'value' => 0,
					'countMin' => 1,
					'countMax' => 4,
				),
				array(
					'rate' => 20,
					'category' => 1,
					'id' => 0,
					'char' => '',
					'value' => 0,
					'countMin' => 80,
					'countMax' => 90,
				),
			),
		),
		'4' => array(
			'name' => '鍾乳洞',
			'fee' => 130,
			'startDirection' => 0,
			'event' => array(
				'none' => 70,
				'drop' => 5,
				'encount' => 25,
			),
			'goal' => array(
				array(
					'rate' => 80,
					'category' => 2,
					'id' => 2,
					'char' => '',
					'value' => 0,
					'countMin' => 3,
					'countMax' => 5,
				),
				array(
					'rate' => 20,
					'category' => 1,
					'id' => 0,
					'char' => '',
					'value' => 0,
					'countMin' => 240,
					'countMax' => 260,
				),
			),
			'drop' => array(
				array(
					'rate' => 80,
					'category' => 2,
					'id' => 2,
					'char' => '',
					'value' => 0,
					'countMin' => 1,
					'countMax' => 4,
				),
				array(
					'rate' => 20,
					'category' => 1,
					'id' => 0,
					'char' => '',
					'value' => 0,
					'countMin' => 90,
					'countMax' => 100,
				),
			),
		),
		'5' => array(
			'name' => '地下巨大湖',
			'fee' => 150,
			'startDirection' => 0,
			'event' => array(
				'none' => 70,
				'drop' => 5,
				'encount' => 25,
			),
			'goal' => array(
				array(
					'rate' => 80,
					'category' => 2,
					'id' => 2,
					'char' => '',
					'value' => 0,
					'countMin' => 3,
					'countMax' => 6,
				),
				array(
					'rate' => 20,
					'category' => 1,
					'id' => 0,
					'char' => '',
					'value' => 0,
					'countMin' => 260,
					'countMax' => 280,
				),
			),
			'drop' => array(
				array(
					'rate' => 80,
					'category' => 2,
					'id' => 2,
					'char' => '',
					'value' => 0,
					'countMin' => 1,
					'countMax' => 3,
				),
				array(
					'rate' => 20,
					'category' => 1,
					'id' => 0,
					'char' => '',
					'value' => 0,
					'countMin' => 100,
					'countMax' => 110,
				),
			),
		),
	),
);
