<?php
//雲ステージの情報
return array(	//各項目詳細はrank1.phpを参照のこと
	'enemy' => array(
		0 => array(
			array(
				'enemyNum' => 501,
				'rate' => 40,
			),
			array(
				'enemyNum' => 502,
				'rate' => 40,
			),
			array(
				'enemyNum' => 503,
				'rate' => 20,
			),
		),
	),
	//'boss' => 504,
	'boss' => array(
					'1'=>'',
					'2'=>'',
					'3'=>'',
					'4'=>'',
					'5'=>'504',
	),
	'stage' => array(
		'1' => array(
			'name' => '空への道',
			'fee' => 370,
			'startDirection' => 0,
			'event' => array(
				'none' => 70,
				'drop' => 5,
				'encount' => 25,
			),
			'goal' => array(
				array(
					'rate' => 80,
					'category' => 2,
					'id' => 5,
					'char' => '',
					'value' => 0,
					'countMin' => 2,
					'countMax' => 5,
				),
				array(
					'rate' => 20,
					'category' => 1,
					'id' => 0,
					'char' => '',
					'value' => 0,
					'countMin' => 500,
					'countMax' => 500,
				),
			),
			'drop' => array(
				array(
					'rate' => 80,
					'category' => 2,
					'id' => 5,
					'char' => '',
					'value' => 0,
					'countMin' => 2,
					'countMax' => 5,
				),
				array(
					'rate' => 20,
					'category' => 1,
					'id' => 0,
					'char' => '',
					'value' => 0,
					'countMin' => 210,
					'countMax' => 220,
				),
			),
		),
		'2' => array(
			'name' => '雲上階段',
			'fee' => 390,
			'startDirection' => 1,
			'event' => array(
				'none' => 70,
				'drop' => 5,
				'encount' => 25,
			),
			'goal' => array(
				array(
					'rate' => 80,
					'category' => 2,
					'id' => 5,
					'char' => '',
					'value' => 0,
					'countMin' => 2,
					'countMax' => 6,
				),
				array(
					'rate' => 20,
					'category' => 1,
					'id' => 0,
					'char' => '',
					'value' => 0,
					'countMin' => 500,
					'countMax' => 520,
				),
			),
			'drop' => array(
				array(
					'rate' => 80,
					'category' => 2,
					'id' => 5,
					'char' => '',
					'value' => 0,
					'countMin' => 2,
					'countMax' => 5,
				),
				array(
					'rate' => 20,
					'category' => 1,
					'id' => 0,
					'char' => '',
					'value' => 0,
					'countMin' => 220,
					'countMax' => 230,
				),
			),
		),
		'3' => array(
			'name' => '真っ白な平原',
			'fee' => 410,
			'startDirection' => 3,
			'event' => array(
				'none' => 70,
				'drop' => 5,
				'encount' => 25,
			),
			'goal' => array(
				array(
					'rate' => 80,
					'category' => 2,
					'id' => 5,
					'char' => '',
					'value' => 0,
					'countMin' => 3,
					'countMax' => 5,
				),
				array(
					'rate' => 20,
					'category' => 1,
					'id' => 0,
					'char' => '',
					'value' => 0,
					'countMin' => 520,
					'countMax' => 540,
				),
			),
			'drop' => array(
				array(
					'rate' => 80,
					'category' => 2,
					'id' => 5,
					'char' => '',
					'value' => 0,
					'countMin' => 1,
					'countMax' => 4,
				),
				array(
					'rate' => 20,
					'category' => 1,
					'id' => 0,
					'char' => '',
					'value' => 0,
					'countMin' => 230,
					'countMax' => 240,
				),
			),
		),
		'4' => array(
			'name' => '龍の巣',
			'fee' => 430,
			'startDirection' => 0,
			'event' => array(
				'none' => 70,
				'drop' => 5,
				'encount' => 25,
			),
			'goal' => array(
				array(
					'rate' => 80,
					'category' => 2,
					'id' => 5,
					'char' => '',
					'value' => 0,
					'countMin' => 2,
					'countMax' => 3,
				),
				array(
					'rate' => 20,
					'category' => 1,
					'id' => 0,
					'char' => '',
					'value' => 0,
					'countMin' => 540,
					'countMax' => 560,
				),
			),
			'drop' => array(
				array(
					'rate' => 80,
					'category' => 2,
					'id' => 5,
					'char' => '',
					'value' => 0,
					'countMin' => 1,
					'countMax' => 4,
				),
				array(
					'rate' => 20,
					'category' => 1,
					'id' => 0,
					'char' => '',
					'value' => 0,
					'countMin' => 240,
					'countMax' => 250,
				),
			),
		),
		'5' => array(
			'name' => '天空の城',
			'fee' => 450,
			'startDirection' => 0,
			'event' => array(
				'none' => 70,
				'drop' => 5,
				'encount' => 25,
			),
			'goal' => array(
				array(
					'rate' => 80,
					'category' => 2,
					'id' => 5,
					'char' => '',
					'value' => 0,
					'countMin' => 3,
					'countMax' => 5,
				),
				array(
					'rate' => 20,
					'category' => 1,
					'id' => 0,
					'char' => '',
					'value' => 0,
					'countMin' => 560,
					'countMax' => 580,
				),
			),
			'drop' => array(
				array(
					'rate' => 80,
					'category' => 2,
					'id' => 5,
					'char' => '',
					'value' => 0,
					'countMin' => 1,
					'countMax' => 3,
				),
				array(
					'rate' => 20,
					'category' => 1,
					'id' => 0,
					'char' => '',
					'value' => 0,
					'countMin' => 250,
					'countMax' => 260,
				),
			),
		),
	),
);
