<?php
//バラステージの情報
return array(	//各項目詳細はrank1.phpを参照のこと
	'enemy' => array(
		0 => array(
			array(
				'enemyNum' => 701,
				'rate' => 40,
			),
			array(
				'enemyNum' => 702,
				'rate' => 40,
			),
			array(
				'enemyNum' => 703,
				'rate' => 20,
			),
		),
	),
	//'boss' => 704,
	'boss' => array(
					'1'=>'',
					'2'=>'',
					'3'=>'',
					'4'=>'',
					'5'=>'704',
	),
	'stage' => array(
		'1' => array(
			'name' => '茨の道',
			'fee' => 570,
			'startDirection' => 0,
			'event' => array(
				'none' => 70,
				'drop' => 5,
				'encount' => 25,
			),
			'goal' => array(
				array(
					'rate' => 80,
					'category' => 2,
					'id' => 6,
					'char' => '',
					'value' => 0,
					'countMin' => 2,
					'countMax' => 4,
				),
				array(
					'rate' => 20,
					'category' => 1,
					'id' => 0,
					'char' => '',
					'value' => 0,
					'countMin' => 700,
					'countMax' => 700,
				),
			),
			'drop' => array(
				array(
					'rate' => 80,
					'category' => 2,
					'id' => 6,
					'char' => '',
					'value' => 0,
					'countMin' => 1,
					'countMax' => 5,
				),
				array(
					'rate' => 20,
					'category' => 1,
					'id' => 0,
					'char' => '',
					'value' => 0,
					'countMin' => 310,
					'countMax' => 320,
				),
			),
		),
		'2' => array(
			'name' => '茨の迷宮',
			'fee' => 590,
			'startDirection' => 1,
			'event' => array(
				'none' => 70,
				'drop' => 5,
				'encount' => 25,
			),
			'goal' => array(
				array(
					'rate' => 80,
					'category' => 2,
					'id' => 6,
					'char' => '',
					'value' => 0,
					'countMin' => 3,
					'countMax' => 5,
				),
				array(
					'rate' => 20,
					'category' => 1,
					'id' => 0,
					'char' => '',
					'value' => 0,
					'countMin' => 700,
					'countMax' => 720,
				),
			),
			'drop' => array(
				array(
					'rate' => 80,
					'category' => 2,
					'id' => 6,
					'char' => '',
					'value' => 0,
					'countMin' => 2,
					'countMax' => 5,
				),
				array(
					'rate' => 20,
					'category' => 1,
					'id' => 0,
					'char' => '',
					'value' => 0,
					'countMin' => 320,
					'countMax' => 330,
				),
			),
		),
		'3' => array(
			'name' => '庭園への入口',
			'fee' => 610,
			'startDirection' => 3,
			'event' => array(
				'none' => 70,
				'drop' => 5,
				'encount' => 25,
			),
			'goal' => array(
				array(
					'rate' => 80,
					'category' => 2,
					'id' => 6,
					'char' => '',
					'value' => 0,
					'countMin' => 2,
					'countMax' => 5,
				),
				array(
					'rate' => 20,
					'category' => 1,
					'id' => 0,
					'char' => '',
					'value' => 0,
					'countMin' => 720,
					'countMax' => 740,
				),
			),
			'drop' => array(
				array(
					'rate' => 80,
					'category' => 2,
					'id' => 6,
					'char' => '',
					'value' => 0,
					'countMin' => 2,
					'countMax' => 5,
				),
				array(
					'rate' => 20,
					'category' => 1,
					'id' => 0,
					'char' => '',
					'value' => 0,
					'countMin' => 330,
					'countMax' => 340,
				),
			),
		),
		'4' => array(
			'name' => '一面のバラ園',
			'fee' => 630,
			'startDirection' => 0,
			'event' => array(
				'none' => 70,
				'drop' => 5,
				'encount' => 25,
			),
			'goal' => array(
				array(
					'rate' => 80,
					'category' => 2,
					'id' => 6,
					'char' => '',
					'value' => 0,
					'countMin' => 2,
					'countMax' => 5,
				),
				array(
					'rate' => 20,
					'category' => 1,
					'id' => 0,
					'char' => '',
					'value' => 0,
					'countMin' => 740,
					'countMax' => 760,
				),
			),
			'drop' => array(
				array(
					'rate' => 80,
					'category' => 2,
					'id' => 6,
					'char' => '',
					'value' => 0,
					'countMin' => 1,
					'countMax' => 6,
				),
				array(
					'rate' => 20,
					'category' => 1,
					'id' => 0,
					'char' => '',
					'value' => 0,
					'countMin' => 340,
					'countMax' => 350,
				),
			),
		),
		'5' => array(
			'name' => 'ローズキャッスル',
			'fee' => 650,
			'startDirection' => 0,
			'event' => array(
				'none' => 70,
				'drop' => 5,
				'encount' => 25,
			),
			'goal' => array(
				array(
					'rate' => 80,
					'category' => 2,
					'id' => 6,
					'char' => '',
					'value' => 0,
					'countMin' => 4,
					'countMax' => 6,
				),
				array(
					'rate' => 20,
					'category' => 1,
					'id' => 0,
					'char' => '',
					'value' => 0,
					'countMin' => 760,
					'countMax' => 780,
				),
			),
			'drop' => array(
				array(
					'rate' => 80,
					'category' => 2,
					'id' => 6,
					'char' => '',
					'value' => 0,
					'countMin' => 4,
					'countMax' => 7,
				),
				array(
					'rate' => 20,
					'category' => 1,
					'id' => 0,
					'char' => '',
					'value' => 0,
					'countMin' => 350,
					'countMax' => 360,
				),
			),
		),
	),
);
