<?php
//未来ステージの情報
return array(	//各項目詳細はrank1.phpを参照のこと
	'enemy' => array(
		0 => array(
			array(
				'enemyNum' => 601,
				'rate' => 40,
			),
			array(
				'enemyNum' => 602,
				'rate' => 20,
			),
			array(
				'enemyNum' => 603,
				'rate' => 40,
			),
		),
	),
	//'boss' => 604,
	'boss' => array(
					'1'=>'',
					'2'=>'',
					'3'=>'',
					'4'=>'',
					'5'=>'604',
	),
	'stage' => array(
		'1' => array(
			'name' => '近未来都市',
			'fee' => 470,
			'startDirection' => 0,
			'event' => array(
				'none' => 70,
				'drop' => 5,
				'encount' => 25,
			),
			'goal' => array(
				array(
					'rate' => 80,
					'category' => 2,
					'id' => 6,
					'char' => '',
					'value' => 0,
					'countMin' => 2,
					'countMax' => 4,
				),
				array(
					'rate' => 20,
					'category' => 1,
					'id' => 0,
					'char' => '',
					'value' => 0,
					'countMin' => 600,
					'countMax' => 600,
				),
			),
			'drop' => array(
				array(
					'rate' => 80,
					'category' => 2,
					'id' => 6,
					'char' => '',
					'value' => 0,
					'countMin' => 1,
					'countMax' => 3,
				),
				array(
					'rate' => 20,
					'category' => 1,
					'id' => 0,
					'char' => '',
					'value' => 0,
					'countMin' => 260,
					'countMax' => 270,
				),
			),
		),
		'2' => array(
			'name' => '車飛び交う道',
			'fee' => 490,
			'startDirection' => 1,
			'event' => array(
				'none' => 70,
				'drop' => 5,
				'encount' => 25,
			),
			'goal' => array(
				array(
					'rate' => 80,
					'category' => 2,
					'id' => 6,
					'char' => '',
					'value' => 0,
					'countMin' => 1,
					'countMax' => 3,
				),
				array(
					'rate' => 20,
					'category' => 1,
					'id' => 0,
					'char' => '',
					'value' => 0,
					'countMin' => 600,
					'countMax' => 620,
				),
			),
			'drop' => array(
				array(
					'rate' => 80,
					'category' => 2,
					'id' => 6,
					'char' => '',
					'value' => 0,
					'countMin' => 1,
					'countMax' => 3,
				),
				array(
					'rate' => 20,
					'category' => 1,
					'id' => 0,
					'char' => '',
					'value' => 0,
					'countMin' => 270,
					'countMax' => 280,
				),
			),
		),
		'3' => array(
			'name' => '銀〇鉄道',
			'fee' => 510,
			'startDirection' => 3,
			'event' => array(
				'none' => 70,
				'drop' => 5,
				'encount' => 25,
			),
			'goal' => array(
				array(
					'rate' => 80,
					'category' => 2,
					'id' => 6,
					'char' => '',
					'value' => 0,
					'countMin' => 2,
					'countMax' => 5,
				),
				array(
					'rate' => 20,
					'category' => 1,
					'id' => 0,
					'char' => '',
					'value' => 0,
					'countMin' => 620,
					'countMax' => 640,
				),
			),
			'drop' => array(
				array(
					'rate' => 80,
					'category' => 2,
					'id' => 6,
					'char' => '',
					'value' => 0,
					'countMin' => 2,
					'countMax' => 4,
				),
				array(
					'rate' => 20,
					'category' => 1,
					'id' => 0,
					'char' => '',
					'value' => 0,
					'countMin' => 280,
					'countMax' => 290,
				),
			),
		),
		'4' => array(
			'name' => 'vs機〇戦士(大嘘)',
			'fee' => 530,
			'startDirection' => 0,
			'event' => array(
				'none' => 70,
				'drop' => 5,
				'encount' => 25,
			),
			'goal' => array(
				array(
					'rate' => 80,
					'category' => 2,
					'id' => 6,
					'char' => '',
					'value' => 0,
					'countMin' => 2,
					'countMax' => 5,
				),
				array(
					'rate' => 20,
					'category' => 1,
					'id' => 0,
					'char' => '',
					'value' => 0,
					'countMin' => 640,
					'countMax' => 660,
				),
			),
			'drop' => array(
				array(
					'rate' => 80,
					'category' => 2,
					'id' => 6,
					'char' => '',
					'value' => 0,
					'countMin' => 1,
					'countMax' => 4,
				),
				array(
					'rate' => 20,
					'category' => 1,
					'id' => 0,
					'char' => '',
					'value' => 0,
					'countMin' => 290,
					'countMax' => 300,
				),
			),
		),
		'5' => array(
			'name' => '宇宙戦争',
			'fee' => 550,
			'startDirection' => 0,
			'event' => array(
				'none' => 70,
				'drop' => 5,
				'encount' => 25,
			),
			'goal' => array(
				array(
					'rate' => 80,
					'category' => 2,
					'id' => 6,
					'char' => '',
					'value' => 0,
					'countMin' => 3,
					'countMax' => 4,
				),
				array(
					'rate' => 20,
					'category' => 1,
					'id' => 0,
					'char' => '',
					'value' => 0,
					'countMin' => 660,
					'countMax' => 680,
				),
			),
			'drop' => array(
				array(
					'rate' => 80,
					'category' => 2,
					'id' => 6,
					'char' => '',
					'value' => 0,
					'countMin' => 4,
					'countMax' => 6,
				),
				array(
					'rate' => 20,
					'category' => 1,
					'id' => 0,
					'char' => '',
					'value' => 0,
					'countMin' => 300,
					'countMax' => 310,
				),
			),
		),
	),
);
