<?php

return array(
	/**		エネミーテンプレート
	'' => array(		//
		'name' => '',
		'hp' => ,
		'attack' => ,
		'diffence' => ,
		'luck' => ,
		'file' => 'monster/',
		'drop' => array(
			array(
				'rate' => ,
				'category' => ,
				'id' => ,
				'char' => '',
				'value' => ,
				'countMin' => ,
				'countMax' => ,
			),
		),
	),
	*/
	'e101' => array(		//蝙蝠
		'name' => 'バット',		//名前
		'hp' => 6,				//HP
		'attack' => 10,			//攻撃力
		'diffence' => 0,		//防御力
		'luck' => 7,			//回避率
		'file' => 'monster/bat.png',	//ファイル名
		'drop' => array(		//撃破時にドロップするもの
			array(			//素材アイテム「木」、presentDBにINSERTするための情報を書く
				'rate' => 60,	//報酬の出現レート
				'category' => 2,	//アイテムカテゴリ(config/itemを参照)
				'id' => 1,		//カテゴリごとのid(各カテゴリのcsvファイルを参照)
				'char' => '',	//charId、素材アイテムのため空を入れる
				'value' => 0,	//素材アイテムのため、空を入れる
				'countMin' => 1,	//最低数
				'countMax' => 2,	//最大数
			),
			array(	//お金
				'rate' => 40,
				'category' => 1,
				'id' => 0,
				'char' => '',
				'value' => 0,
				'countMin' => 10,
				'countMax' => 20,
			),
		),
	),
	'e102' => array(		//妖精
		'name' => 'フェアリー',
		'hp' => 4,
		'attack' => 8,
		'diffence' => 0,
		'luck' => 10,
		'file' => 'monster/fairy.png',
		'drop' => array(
			array(
				'rate' => 50,
				'category' => 2,
				'id' => 1,
				'char' => '',
				'value' => 0,
				'countMin' => 2,
				'countMax' => 5,
			),
			array(
				'rate' => 50,
				'category' => 1,
				'id' => 0,
				'char' => '',
				'value' => 0,
				'countMin' => 20,
				'countMax' => 50,
			),
		),
	),
	'e103' => array(		//ラビット
		'name' => 'ラビット',
		'hp' => 5,
		'attack' => 6,
		'diffence' => 0,
		'luck' => 10,
		'file' => 'monster/rabbit.png',
		'drop' => array(
			array(
				'rate' => 50,
				'category' => 2,
				'id' => 1,
				'char' => '',
				'value' => 0,
				'countMin' => 2,
				'countMax' => 5,
			),
			array(
				'rate' => 50,
				'category' => 1,
				'id' => 0,
				'char' => '',
				'value' => 0,
				'countMin' => 20,
				'countMax' => 50,
			),
		),
	),
	'e104' => array(		//ボス：キングベアー
		'name' => 'キングベアー',
		'hp' => 20,
		'attack' => 20,
		'diffence' => 3,
		'luck' => 7,
		'file' => 'monster/kingbear.png',
		'drop' => array(
			array(
				'rate' => 40,
				'category' => 2,
				'id' => 1,
				'char' => '',
				'value' => 0,
				'countMin' => 2,
				'countMax' => 5,
			),
			array(
				'rate' => 30,
				'category' => 2,
				'id' => 2,
				'char' => '',
				'value' => 0,
				'countMin' => 1,
				'countMax' => 3,
			),
			array(
				'rate' => 30,
				'category' => 1,
				'id' => 0,
				'char' => '',
				'value' => 0,
				'countMin' => 100,
				'countMax' => 150,
			),
		),
	),
	'e201' => array(		//獣人
		'name' => 'ビースト',
		'hp' => 10,
		'attack' => 25,
		'diffence' => 4,
		'luck' => 12,
		'file' => 'monster/beast.png',
		'drop' => array(
			array(
				'rate' => 50,
				'category' => 2,
				'id' => 2,
				'char' => '',
				'value' => 0,
				'countMin' => 2,
				'countMax' => 5,
			),
			array(
				'rate' => 20,
				'category' => 2,
				'id' => 1,
				'char' => '',
				'value' => 0,
				'countMin' => 4,
				'countMax' => 7,
			),
			array(
				'rate' => 30,
				'category' => 1,
				'id' => 0,
				'char' => '',
				'value' => 0,
				'countMin' => 30,
				'countMax' => 60,
			),
		),
	),
	'e202' => array(		//フード
		'name' => 'フードマン',
		'hp' => 12,
		'attack' => 23,
		'diffence' => 3,
		'luck' => 7,
		'file' => 'monster/hood.png',
		'drop' => array(
			array(
				'rate' => 50,
				'category' => 2,
				'id' => 2,
				'char' => '',
				'value' => 0,
				'countMin' => 2,
				'countMax' => 5,
			),
			array(
				'rate' => 10,
				'category' => 2,
				'id' => 1,
				'char' => '',
				'value' => 0,
				'countMin' => 1,
				'countMax' => 5,
			),
			array(
				'rate' => 40,
				'category' => 1,
				'id' => 0,
				'char' => '',
				'value' => 0,
				'countMin' => 45,
				'countMax' => 90,
			),
		),
	),
	'e203' => array(		//蛇
		'name' => 'スネーク',
		'hp' => 9,
		'attack' => 18,
		'diffence' => 5,
		'luck' => 15,
		'file' => 'monster/snake.png',
		'drop' => array(
			array(
				'rate' => 60,
				'category' => 2,
				'id' => 2,
				'char' => '',
				'value' => 0,
				'countMin' => 1,
				'countMax' => 5,
			),
			array(
				'rate' => 40,
				'category' => 1,
				'id' => 0,
				'char' => '',
				'value' => 0,
				'countMin' => 50,
				'countMax' => 100,
			),
		),
	),
	'e204' => array(		//ボス：ドラゴン
		'name' => 'ドラゴン',
		'hp' => 24,
		'attack' => 65,
		'diffence' => 10,
		'luck' => 10,
		'file' => 'monster/dragon.png',
		'drop' => array(
			array(
				'rate' => 40,
				'category' => 2,
				'id' => 2,
				'char' => '',
				'value' => 0,
				'countMin' => 1,
				'countMax' => 5,
			),
			array(
				'rate' => 40,
				'category' => 2,
				'id' => 3,
				'char' => '',
				'value' => 0,
				'countMin' => 1,
				'countMax' => 5,
			),
			array(
				'rate' => 20,
				'category' => 1,
				'id' => 0,
				'char' => '',
				'value' => 0,
				'countMin' => 50,
				'countMax' => 100,
			),
		),
	),
	'e301' => array(		//騎士
		'name' => '騎士',
		'hp' => 18,
		'attack' => 80,
		'diffence' => 18,
		'luck' => 10,
		'file' => 'monster/knight.png',
		'drop' => array(
			array(
				'rate' => 50,
				'category' => 2,
				'id' => 3,
				'char' => '',
				'value' => 0,
				'countMin' => 2,
				'countMax' => 6,
			),
			array(
				'rate' => 30,
				'category' => 2,
				'id' => 2,
				'char' => '',
				'value' => 0,
				'countMin' => 1,
				'countMax' => 5,
			),
			array(
				'rate' => 20,
				'category' => 1,
				'id' => 0,
				'char' => '',
				'value' => 0,
				'countMin' => 55,
				'countMax' => 120,
			),
		),
	),
	'e302' => array(		//スケルトン
		'name' => 'スケルトン',
		'hp' => 16,
		'attack' => 85,
		'diffence' => 20,
		'luck' => 15,
		'file' => 'monster/skeleton.png',
		'drop' => array(
			array(
				'rate' => 50,
				'category' => 2,
				'id' => 3,
				'char' => '',
				'value' => 0,
				'countMin' => 1,
				'countMax' => 5,
			),
			array(
				'rate' => 10,
				'category' => 2,
				'id' => 2,
				'char' => '',
				'value' => 0,
				'countMin' => 1,
				'countMax' => 3,
			),
			array(
				'rate' => 40,
				'category' => 1,
				'id' => 0,
				'char' => '',
				'value' => 0,
				'countMin' => 70,
				'countMax' => 150,
			),
		),
	),
	'e303' => array(		//ゴースト
		'name' => 'ゴースト',
		'hp' => 14,
		'attack' => 85,
		'diffence' => 20,
		'luck' => 15,
		'file' => 'monster/ghost.png',
		'drop' => array(
			array(
				'rate' => 50,
				'category' => 2,
				'id' => 3,
				'char' => '',
				'value' => 0,
				'countMin' => 1,
				'countMax' => 5,
			),
			array(
				'rate' => 10,
				'category' => 2,
				'id' => 2,
				'char' => '',
				'value' => 0,
				'countMin' => 1,
				'countMax' => 3,
			),
			array(
				'rate' => 40,
				'category' => 1,
				'id' => 0,
				'char' => '',
				'value' => 0,
				'countMin' => 70,
				'countMax' => 150,
			),
		),
	),
	'e304' => array(		//ボス：ゾンビ
		'name' => 'ゾンビ',
		'hp' => 60,
		'attack' => 112,
		'diffence' => 35,
		'luck' => 16,
		'file' => 'monster/zombie.png',
		'drop' => array(
			array(
				'rate' => 50,
				'category' => 2,
				'id' => 3,
				'char' => '',
				'value' => 0,
				'countMin' => 1,
				'countMax' => 5,
			),
			array(
				'rate' => 10,
				'category' => 2,
				'id' => 4,
				'char' => '',
				'value' => 0,
				'countMin' => 1,
				'countMax' => 3,
			),
			array(
				'rate' => 40,
				'category' => 1,
				'id' => 0,
				'char' => '',
				'value' => 0,
				'countMin' => 70,
				'countMax' => 150,
			),
		),
	),
	'e401' => array(		//スライム
		'name' => 'スライム',
		'hp' => 24,
		'attack' => 130,
		'diffence' => 45,
		'luck' => 10,
		'file' => 'monster/slime.png',
		'drop' => array(
			array(
				'rate' => 40,
				'category' => 2,
				'id' => 4,
				'char' => '',
				'value' => 0,
				'countMin' => 1,
				'countMax' => 3,
			),
			array(
				'rate' => 20,
				'category' => 2,
				'id' => 3,
				'char' => '',
				'value' => 0,
				'countMin' => 4,
				'countMax' => 7,
			),
			array(
				'rate' => 10,
				'category' => 2,
				'id' => 2,
				'char' => '',
				'value' => 0,
				'countMin' => 1,
				'countMax' => 6,
			),
			array(
				'rate' => 30,
				'category' => 1,
				'id' => 0,
				'char' => '',
				'value' => 0,
				'countMin' => 50,
				'countMax' => 75,
			),
		),
	),
	'e402' => array(		//熊
		'name' => 'ベアー',
		'hp' => 28,
		'attack' => 135,
		'diffence' => 43,
		'luck' => 40,
		'file' => 'monster/bear.png',
		'drop' => array(
			array(
				'rate' => 50,
				'category' => 2,
				'id' => 4,
				'char' => '',
				'value' => 0,
				'countMin' => 2,
				'countMax' => 6,
			),
			array(
				'rate' => 30,
				'category' => 2,
				'id' => 3,
				'char' => '',
				'value' => 0,
				'countMin' => 3,
				'countMax' => 6,
			),
			array(
				'rate' => 20,
				'category' => 1,
				'id' => 0,
				'char' => '',
				'value' => 0,
				'countMin' => 60,
				'countMax' => 100,
			),
		),
	),
	'e403' => array(		//さしみタンポポ
		'name' => 'さしみタンポポ',
		'hp' => 28,
		'attack' => 132,
		'diffence' => 40,
		'luck' => 30,
		'file' => 'monster/sashimidandelion.png',
		'drop' => array(
			array(
				'rate' => 50,
				'category' => 2,
				'id' => 4,
				'char' => '',
				'value' => 0,
				'countMin' => 2,
				'countMax' => 6,
			),
			array(
				'rate' => 30,
				'category' => 2,
				'id' => 3,
				'char' => '',
				'value' => 0,
				'countMin' => 3,
				'countMax' => 6,
			),
			array(
				'rate' => 20,
				'category' => 1,
				'id' => 0,
				'char' => '',
				'value' => 0,
				'countMin' => 60,
				'countMax' => 100,
			),
		),
	),
	'e404' => array(		//ボス：アンドロイド
		'name' => 'アンドロイド',
		'hp' => 74,
		'attack' => 144,
		'diffence' => 66,
		'luck' => 55,
		'file' => 'monster/android.png',
		'drop' => array(
			array(
				'rate' => 50,
				'category' => 2,
				'id' => 4,
				'char' => '',
				'value' => 0,
				'countMin' => 2,
				'countMax' => 6,
			),
			array(
				'rate' => 30,
				'category' => 2,
				'id' => 5,
				'char' => '',
				'value' => 0,
				'countMin' => 3,
				'countMax' => 6,
			),
			array(
				'rate' => 20,
				'category' => 1,
				'id' => 0,
				'char' => '',
				'value' => 0,
				'countMin' => 60,
				'countMax' => 100,
			),
		),
	),
	'e501' => array(		//雲
		'name' => 'スコール',
		'hp' => 32,
		'attack' => 165,
		'diffence' => 85,
		'luck' => 60,
		'file' => 'monster/cloud.png',
		'drop' => array(
			array(
				'rate' => 50,
				'category' => 2,
				'id' => 5,
				'char' => '',
				'value' => 0,
				'countMin' => 2,
				'countMax' => 5,
			),
			array(
				'rate' => 30,
				'category' => 2,
				'id' => 4,
				'char' => '',
				'value' => 0,
				'countMin' => 2,
				'countMax' => 5,
			),
			array(
				'rate' => 20,
				'category' => 1,
				'id' => 0,
				'char' => '',
				'value' => 0,
				'countMin' => 60,
				'countMax' => 130,
			),
		),
	),
	'e502' => array(		//天使
		'name' => 'エンジェル',
		'hp' => 28,
		'attack' => 160,
		'diffence' => 85,
		'luck' => 60,
		'file' => 'monster/angel.png',
		'drop' => array(
			array(
				'rate' => 40,
				'category' => 2,
				'id' => 5,
				'char' => '',
				'value' => 0,
				'countMin' => 2,
				'countMax' => 5,
			),
			array(
				'rate' => 20,
				'category' => 2,
				'id' => 4,
				'char' => '',
				'value' => 0,
				'countMin' => 3,
				'countMax' => 7,
			),
			array(
				'rate' => 10,
				'category' => 2,
				'id' => 3,
				'char' => '',
				'value' => 0,
				'countMin' => 5,
				'countMax' => 10,
			),
			array(
				'rate' => 30,
				'category' => 1,
				'id' => 0,
				'char' => '',
				'value' => 0,
				'countMin' => 70,
				'countMax' =>180,
			),
		),
	),
	'e503' => array(		//黒天使
		'name' => 'ブラックエンジェル',
		'hp' => 30,
		'attack' => 163,
		'diffence' => 163,
		'luck' => 60,
		'file' => 'monster/blackangel.png',
		'drop' => array(
			array(
				'rate' => 40,
				'category' => 2,
				'id' => 5,
				'char' => '',
				'value' => 0,
				'countMin' => 2,
				'countMax' => 5,
			),
			array(
				'rate' => 20,
				'category' => 2,
				'id' => 4,
				'char' => '',
				'value' => 0,
				'countMin' => 3,
				'countMax' => 7,
			),
			array(
				'rate' => 10,
				'category' => 2,
				'id' => 3,
				'char' => '',
				'value' => 0,
				'countMin' => 5,
				'countMax' => 10,
			),
			array(
				'rate' => 30,
				'category' => 1,
				'id' => 0,
				'char' => '',
				'value' => 0,
				'countMin' => 70,
				'countMax' =>180,
			),
		),
	),
	'e504' => array(		//ボス:ペガサス
		'name' => 'ペガサス',
		'hp' => 80,
		'attack' => 171,
		'diffence' => 100,
		'luck' => 70,
		'file' => 'monster/pegasus.png',
		'drop' => array(
			array(
				'rate' => 50,
				'category' => 2,
				'id' => 5,
				'char' => '',
				'value' => 0,
				'countMin' => 2,
				'countMax' => 5,
			),
			array(
				'rate' => 30,
				'category' => 2,
				'id' => 6,
				'char' => '',
				'value' => 0,
				'countMin' => 2,
				'countMax' => 5,
			),
			array(
				'rate' => 20,
				'category' => 1,
				'id' => 0,
				'char' => '',
				'value' => 0,
				'countMin' => 60,
				'countMax' => 130,
			),
		),
	),
	'e601' => array(		//ロボット
		'name' => 'ロボット',
		'hp' => 25,
		'attack' => 200,
		'diffence' => 100,
		'luck' => 55,
		'file' => 'monster/robot.png',
		'drop' => array(
			array(
				'rate' => 40,
				'category' => 2,
				'id' => 6,
				'char' => '',
				'value' => 0,
				'countMin' => 2,
				'countMax' => 5,
			),
			array(
				'rate' => 20,
				'category' => 2,
				'id' => 5,
				'char' => '',
				'value' => 0,
				'countMin' => 3,
				'countMax' => 7,
			),
			array(
				'rate' => 10,
				'category' => 2,
				'id' => 4,
				'char' => '',
				'value' => 0,
				'countMin' => 5,
				'countMax' => 8,
			),
			array(
				'rate' => 30,
				'category' => 1,
				'id' => 0,
				'char' => '',
				'value' => 0,
				'countMin' => 80,
				'countMax' => 140,
			),
		),
	),
	'e602' => array(		//魔法少女
		'name' => '魔法少女(?)',
		'hp' => 34,
		'attack' => 203,
		'diffence' => 105,
		'luck' => 60,
		'file' => 'monster/magicalgirl.png',
		'drop' => array(
			array(
				'rate' => 50,
				'category' => 2,
				'id' => 6,
				'char' => '',
				'value' => 0,
				'countMin' => 5,
				'countMax' => 6,
			),
			array(
				'rate' => 30,
				'category' => 2,
				'id' => 5,
				'char' => '',
				'value' => 0,
				'countMin' => 4,
				'countMax' => 7,
			),
			array(
				'rate' => 20,
				'category' => 1,
				'id' => 0,
				'char' => '',
				'value' => 0,
				'countMin' => 60,
				'countMax' => 170,
			),
		),
	),
	'e603' => array(		//ポリスロボ
		'name' => 'ポリスロボ',
		'hp' => 29,
		'attack' => 198,
		'diffence' => 102,
		'luck' => 56,
		'file' => 'monster/robotpoliceman.png',
		'drop' => array(
			array(
				'rate' => 50,
				'category' => 2,
				'id' => 6,
				'char' => '',
				'value' => 0,
				'countMin' => 5,
				'countMax' => 6,
			),
			array(
				'rate' => 30,
				'category' => 2,
				'id' => 5,
				'char' => '',
				'value' => 0,
				'countMin' => 4,
				'countMax' => 7,
			),
			array(
				'rate' => 20,
				'category' => 1,
				'id' => 0,
				'char' => '',
				'value' => 0,
				'countMin' => 60,
				'countMax' => 170,
			),
		),
	),
	'e604' => array(		//ボス：サイバーガール
		'name' => 'サイバーガール',
		'hp' => 85,
		'attack' => 208,
		'diffence' => 130,
		'luck' => 90,
		'file' => 'monster/cybergirl.png',
		'drop' => array(
			array(
				'rate' => 50,
				'category' => 2,
				'id' => 6,
				'char' => '',
				'value' => 0,
				'countMin' => 5,
				'countMax' => 6,
			),
			array(
				'rate' => 30,
				'category' => 2,
				'id' => 5,
				'char' => '',
				'value' => 0,
				'countMin' => 4,
				'countMax' => 7,
			),
			array(
				'rate' => 20,
				'category' => 1,
				'id' => 0,
				'char' => '',
				'value' => 0,
				'countMin' => 60,
				'countMax' => 170,
			),
		),
	),
	'e701' => array(		//バラ
		'name' => 'バラ',
		'hp' => 38,
		'attack' => 200,
		'diffence' => 137,
		'luck' => 84,
		'file' => 'monster/bara.png',
		'drop' => array(
			array(
				'rate' => 50,
				'category' => 2,
				'id' => 6,
				'char' => '',
				'value' => 0,
				'countMin' => 2,
				'countMax' => 5,
			),
			array(
				'rate' => 30,
				'category' => 2,
				'id' => 5,
				'char' => '',
				'value' => 0,
				'countMin' => 2,
				'countMax' => 10,
			),
			array(
				'rate' => 20,
				'category' => 1,
				'id' => 0,
				'char' => '',
				'value' => 0,
				'countMin' => 70,
				'countMax' => 160,
			),
		),
	),
	'e702' => array(		//庭師
		'name' => '庭師',
		'hp' => 41,
		'attack' => 202,
		'diffence' => 140,
		'luck' => 72,
		'file' => 'monster/gardener.png',
		'drop' => array(
			array(
				'rate' => 50,
				'category' => 2,
				'id' => 6,
				'char' => '',
				'value' => 0,
				'countMin' => 2,
				'countMax' => 5,
			),
			array(
				'rate' => 30,
				'category' => 2,
				'id' => 5,
				'char' => '',
				'value' => 0,
				'countMin' => 2,
				'countMax' => 10,
			),
			array(
				'rate' => 20,
				'category' => 1,
				'id' => 0,
				'char' => '',
				'value' => 0,
				'countMin' => 70,
				'countMax' => 160,
			),
		),
	),
	'e703' => array(		//サキュバス
		'name' => 'サキュバス',
		'hp' => 45,
		'attack' => 205,
		'diffence' => 142,
		'luck' => 98,
		'file' => 'monster/succubus.png',
		'drop' => array(
			array(
				'rate' => 40,
				'category' => 2,
				'id' => 6,
				'char' => '',
				'value' => 0,
				'countMin' => 2,
				'countMax' => 7,
			),
			array(
				'rate' => 20,
				'category' => 2,
				'id' => 5,
				'char' => '',
				'value' => 0,
				'countMin' => 2,
				'countMax' => 10,
			),
			array(
				'rate' => 10,
				'category' => 2,
				'id' => 4,
				'char' => '',
				'value' => 0,
				'countMin' => 10,
				'countMax' => 15,
			),
			array(
				'rate' => 30,
				'category' => 1,
				'id' => 0,
				'char' => '',
				'value' => 0,
				'countMin' => 100,
				'countMax' => 170,
			),
		),
	),
	'e704' => array(		//ボス：ゴーレム
		'name' => 'ゴーレム',
		'hp' => 60,
		'attack' => 210,
		'diffence' => 260,
		'luck' => 40,
		'file' => 'monster/golem.png',
		'drop' => array(
			array(
				'rate' => 40,
				'category' => 2,
				'id' => 6,
				'char' => '',
				'value' => 0,
				'countMin' => 5,
				'countMax' => 8,
			),
			array(
				'rate' => 20,
				'category' => 2,
				'id' => 5,
				'char' => '',
				'value' => 0,
				'countMin' => 3,
				'countMax' => 5,
			),
			array(
				'rate' => 10,
				'category' => 2,
				'id' => 4,
				'char' => '',
				'value' => 0,
				'countMin' => 7,
				'countMax' => 12,
			),
			array(
				'rate' => 30,
				'category' => 1,
				'id' => 0,
				'char' => '',
				'value' => 0,
				'countMin' => 100,
				'countMax' => 280,
			),
		),
	),
	//大迷宮バフォメット1F　敵
	'ee1011' => array(		// バット
		'name' => 'バット',
		'hp' => 4,
		'attack' => 25,
		'diffence' => 2,
		'luck' => 22,
		'file' => 'monster/event1/e1bat.png',
		'drop' => array(
			array(
				'rate' => 20,
				'category' => 2,
				'id' => 101,
				'char' => '',
				'value' => 0,
				'countMin' => 1,
				'countMax' => 4,
			),
			array(
				'rate' => 80,
				'category' => 1,
				'id' => 0,
				'char' => '',
				'value' => 0,
				'countMin' => 10,
				'countMax' => 50,
			),
		),
	),
	'ee1021' => array(		// スネーク
		'name' => 'スネーク',
		'hp' => 5,
		'attack' => 22,
		'diffence' => 3,
		'luck' => 17,
		'file' => 'monster/event1/e1snake.png',
		'drop' => array(
			array(
				'rate' => 20,
				'category' => 2,
				'id' => 101,
				'char' => '',
				'value' => 0,
				'countMin' => 1,
				'countMax' => 4,
			),
			array(
				'rate' => 80,
				'category' => 1,
				'id' => 0,
				'char' => '',
				'value' => 0,
				'countMin' => 10,
				'countMax' => 50,
			),
		),
	),
	'ee1031' => array(		// ビースト
		'name' => 'ビースト',
		'hp' => 5,
		'attack' => 43,
		'diffence' => 2,
		'luck' => 12,
		'file' => 'monster/event1/e1beast.png',
		'drop' => array(
			array(
				'rate' => 40,
				'category' => 2,
				'id' => 101,
				'char' => '',
				'value' => 0,
				'countMin' => 1,
				'countMax' => 4,
			),
			array(
				'rate' => 80,
				'category' => 1,
				'id' => 0,
				'char' => '',
				'value' => 0,
				'countMin' => 10,
				'countMax' => 50,
			),
		),
	),
	'ee1041' => array(		// スライム
		'name' => 'スライム',
		'hp' => 6,
		'attack' => 20,
		'diffence' => 2,
		'luck' => 12,
		'file' => 'monster/event1/e1slime.png',
		'drop' => array(
			array(
				'rate' => 20,
				'category' => 2,
				'id' => 101,
				'char' => '',
				'value' => 0,
				'countMin' => 1,
				'countMax' => 4,
			),
			array(
				'rate' => 80,
				'category' => 1,
				'id' => 0,
				'char' => '',
				'value' => 0,
				'countMin' => 10,
				'countMax' => 50,
			),
		),
	),
	'ee1051' => array(		// ゴースト
		'name' => 'ゴースト',
		'hp' => 5,
		'attack' => 41,
		'diffence' => 2,
		'luck' => 37,
		'file' => 'monster/event1/e1ghost.png',
		'drop' => array(
			array(
				'rate' => 20,
				'category' => 2,
				'id' => 101,
				'char' => '',
				'value' => 0,
				'countMin' => 1,
				'countMax' => 4,
			),
			array(
				'rate' => 80,
				'category' => 1,
				'id' => 0,
				'char' => '',
				'value' => 0,
				'countMin' => 10,
				'countMax' => 50,
			),
		),
	),

	//大迷宮バフォメット2F　敵
	'ee1012' => array(		// バット
		'name' => '彷徨うバット',
		'hp' => 22,
		'attack' => 115,
		'diffence' => 25,
		'luck' => 92,
		'file' => 'monster/event1/e1bat.png',
		'drop' => array(
			array(
				'rate' => 20,
				'category' => 2,
				'id' => 101,
				'char' => '',
				'value' => 0,
				'countMin' => 2,
				'countMax' => 8,
			),
			array(
				'rate' => 80,
				'category' => 1,
				'id' => 0,
				'char' => '',
				'value' => 0,
				'countMin' => 20,
				'countMax' => 80,
			),
		),
	),
	'ee1022' => array(		// スネーク
		'name' => 'ジムグリ',
		'hp' => 25,
		'attack' => 120,
		'diffence' => 30,
		'luck' => 90,
		'file' => 'monster/event1/e1snake.png',
		'drop' => array(
			array(
				'rate' => 20,
				'category' => 2,
				'id' => 101,
				'char' => '',
				'value' => 0,
				'countMin' => 2,
				'countMax' => 8,
			),
			array(
				'rate' => 80,
				'category' => 1,
				'id' => 0,
				'char' => '',
				'value' => 0,
				'countMin' => 20,
				'countMax' => 80,
			),
		),
	),
	'ee1032' => array(		// ビースト
		'name' => '獰猛なビースト',
		'hp' => 28,
		'attack' => 125,
		'diffence' => 35,
		'luck' => 22,
		'file' => 'monster/event1/e1beast.png',
		'drop' => array(
			array(
				'rate' => 20,
				'category' => 2,
				'id' => 101,
				'char' => '',
				'value' => 0,
				'countMin' => 2,
				'countMax' => 8,
			),
			array(
				'rate' => 80,
				'category' => 1,
				'id' => 0,
				'char' => '',
				'value' => 0,
				'countMin' => 20,
				'countMax' => 80,
			),
		),
	),
	'ee1042' => array(		// スライム
		'name' => 'スララ・イム',
		'hp' => 6,
		'attack' => 100,
		'diffence' => 70,
		'luck' => 7000,
		'file' => 'monster/event1/e1slime.png',
		'drop' => array(
			array(
				'rate' => 50,
				'category' => 2,
				'id' => 101,
				'char' => '',
				'value' => 0,
				'countMin' => 5,
				'countMax' => 25,
			),
			array(
				'rate' => 50,
				'category' => 1,
				'id' => 0,
				'char' => '',
				'value' => 0,
				'countMin' => 100,
				'countMax' => 600,
			),
		),
	),
	'ee1052' => array(		// ゴースト
		'name' => '怨霊',
		'hp' => 32,
		'attack' => 130,
		'diffence' => 25,
		'luck' => 10,
		'file' => 'monster/event1/e1ghost.png',
		'drop' => array(
			array(
				'rate' => 20,
				'category' => 2,
				'id' => 101,
				'char' => '',
				'value' => 0,
				'countMin' => 2,
				'countMax' => 8,
			),
			array(
				'rate' => 80,
				'category' => 1,
				'id' => 0,
				'char' => '',
				'value' => 0,
				'countMin' => 20,
				'countMax' => 80,
			),
		),
	),
	//大迷宮バフォメット3F　敵
	'ee1013' => array(		// バット
		'name' => 'ジャイアント・バット',
		'hp' => 46,
		'attack' => 210,
		'diffence' => 15,
		'luck' => 400,
		'file' => 'monster/event1/e1bat.png',
		'drop' => array(
			array(
				'rate' => 30,
				'category' => 2,
				'id' => 101,
				'char' => '',
				'value' => 0,
				'countMin' => 3,
				'countMax' => 9,
			),
			array(
				'rate' => 70,
				'category' => 1,
				'id' => 0,
				'char' => '',
				'value' => 0,
				'countMin' => 50,
				'countMax' => 150,
			),
		),
	),
	'ee1023' => array(		// スネーク
		'name' => '獰猛なジムグリ',
		'hp' => 38,
		'attack' => 210,
		'diffence' => 60,
		'luck' => 20,
		'file' => 'monster/event1/e1snake.png',
		'drop' => array(
			array(
				'rate' => 30,
				'category' => 2,
				'id' => 101,
				'char' => '',
				'value' => 0,
				'countMin' => 3,
				'countMax' => 9,
			),
			array(
				'rate' => 70,
				'category' => 1,
				'id' => 0,
				'char' => '',
				'value' => 0,
				'countMin' => 50,
				'countMax' => 150,
			),
		),
	),
	'ee1033' => array(		// ビースト
		'name' => 'トトト・ロ・ビースト',
		'hp' => 65,
		'attack' => 310,
		'diffence' => 20,
		'luck' => 20,
		'file' => 'monster/event1/e1beast.png',
		'drop' => array(
			array(
				'rate' => 35,
				'category' => 2,
				'id' => 101,
				'char' => '',
				'value' => 0,
				'countMin' => 4,
				'countMax' => 12,
			),
			array(
				'rate' => 65,
				'category' => 1,
				'id' => 0,
				'char' => '',
				'value' => 0,
				'countMin' => 100,
				'countMax' => 500,
			),
		),
	),
	'ee1043' => array(		// スライム
		'name' => '彷徨うスライム',
		'hp' => 70,
		'attack' => 190,
		'diffence' => 30,
		'luck' => 10,
		'file' => 'monster/event1/e1slime.png',
		'drop' => array(
			array(
				'rate' => 30,
				'category' => 2,
				'id' => 101,
				'char' => '',
				'value' => 0,
				'countMin' => 3,
				'countMax' => 9,
			),
			array(
				'rate' => 70,
				'category' => 1,
				'id' => 0,
				'char' => '',
				'value' => 0,
				'countMin' => 50,
				'countMax' => 150,
			),
		),
	),
	'ee1053' => array(		// ゴースト
		'name' => '憎む者',
		'hp' => 60,
		'attack' => 240,
		'diffence' => 26,
		'luck' => 1500,
		'file' => 'monster/event1/e1ghost.png',
		'drop' => array(
			array(
				'rate' => 30,
				'category' => 2,
				'id' => 101,
				'char' => '',
				'value' => 0,
				'countMin' => 3,
				'countMax' => 10,
			),
			array(
				'rate' => 70,
				'category' => 1,
				'id' => 0,
				'char' => '',
				'value' => 0,
				'countMin' => 50,
				'countMax' => 150,
			),
		),
	),
	//大迷宮バフォメット4F　敵
	'ee1014' => array(		// バット
		'name' => 'バンティ',
		'hp' => 46,
		'attack' => 280,
		'diffence' => 15,
		'luck' => 400,
		'file' => 'monster/event1/e1bat.png',
		'drop' => array(
			array(
				'rate' => 30,
				'category' => 2,
				'id' => 101,
				'char' => '',
				'value' => 0,
				'countMin' => 3,
				'countMax' => 9,
			),
			array(
				'rate' => 70,
				'category' => 1,
				'id' => 0,
				'char' => '',
				'value' => 0,
				'countMin' => 50,
				'countMax' => 150,
			),
		),
	),
	'ee1024' => array(		// スネーク
		'name' => '脛イク',
		'hp' => 38,
		'attack' => 280,
		'diffence' => 60,
		'luck' => 20,
		'file' => 'monster/event1/e1snake.png',
		'drop' => array(
			array(
				'rate' => 30,
				'category' => 2,
				'id' => 101,
				'char' => '',
				'value' => 0,
				'countMin' => 3,
				'countMax' => 9,
			),
			array(
				'rate' => 70,
				'category' => 1,
				'id' => 0,
				'char' => '',
				'value' => 0,
				'countMin' => 50,
				'countMax' => 150,
			),
		),
	),
	'ee1034' => array(		// ビースト
		'name' => 'グレムリン',
		'hp' => 85,
		'attack' => 310,
		'diffence' => 20,
		'luck' => 20,
		'file' => 'monster/event1/e1beast.png',
		'drop' => array(
			array(
				'rate' => 35,
				'category' => 2,
				'id' => 101,
				'char' => '',
				'value' => 0,
				'countMin' => 4,
				'countMax' => 12,
			),
			array(
				'rate' => 65,
				'category' => 1,
				'id' => 0,
				'char' => '',
				'value' => 0,
				'countMin' => 100,
				'countMax' => 500,
			),
		),
	),
	'ee1044' => array(		// スライム
		'name' => 'ブッチ',
		'hp' => 40,
		'attack' => 260,
		'diffence' => 80,
		'luck' => 10,
		'file' => 'monster/event1/e1slime.png',
		'drop' => array(
			array(
				'rate' => 40,
				'category' => 2,
				'id' => 101,
				'char' => '',
				'value' => 0,
				'countMin' => 4,
				'countMax' => 12,
			),
			array(
				'rate' => 60,
				'category' => 1,
				'id' => 0,
				'char' => '',
				'value' => 0,
				'countMin' => 100,
				'countMax' => 200,
			),
		),
	),
	'ee1054' => array(		// ゴースト
		'name' => '死霊メイド',
		'hp' => 90,
		'attack' => 275,
		'diffence' => 15,
		'luck' => 1500,
		'file' => 'monster/event1/e1ghost.png',
		'drop' => array(
			array(
				'rate' => 40,
				'category' => 2,
				'id' => 101,
				'char' => '',
				'value' => 0,
				'countMin' => 4,
				'countMax' => 12,
			),
			array(
				'rate' => 60,
				'category' => 1,
				'id' => 0,
				'char' => '',
				'value' => 0,
				'countMin' => 100,
				'countMax' => 200,
			),
		),
	),
	
	// 中ボス
	'ee106' => array(		// 中ボス　サキュバス
		'name' => 'サ・キュバス',
		'hp' => 30,
		'attack' => 175,
		'diffence' => 28,
		'luck' => 2000,
		'file' => 'monster/event1/e1succubus.png',
		'drop' => array(
			array(
				'rate' => 100,
				'category' => 2,
				'id' => 101,
				'char' => '',
				'value' => 0,
				'countMin' => 15,
				'countMax' => 35,
			),
		),
	),
	'ee107' => array(		// 中ボス　ゴーレム
		'name' => 'コロッサス',
		'hp' => 110,
		'attack' => 300,
		'diffence' => 45,
		'luck' => 10,
		'file' => 'monster/event1/e1golem.png',
		'drop' => array(
			array(
				'rate' => 100,
				'category' => 2,
				'id' => 101,
				'char' => '',
				'value' => 0,
				'countMin' => 45,
				'countMax' => 65,
			),
		),
	),
	'ee105' => array(		//　バフォメット
		'name' => 'バフォメット',
		'hp' => 600,
		'attack' => 340,
		'diffence' => 20,
		'luck' => 100,
		'file' => 'monster/event1/e1baphomet.png',
		'drop' => array(
			array(
				'rate' => 97,
				'category' => 2,
				'id' => 101,
				'char' => '',
				'value' => 0,
				'countMin' => 100,
				'countMax' => 300,
			),
			array(
				'rate' => 3,
				'category' => 3,
				'id' => 1,
				'char' => 'e',
				'value' => 160,
				'countMin' => 1,
				'countMax' => 1,
			),
		),
	),
);